#
#  Copyright (c) 2018 Atos, and others
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License 2.0
#  which accompanies this distribution, and is available at
#  https://www.eclipse.org/legal/epl-2.0/
#
#  Contributors:
#  Atos - initial implementation
#

server:
  applicationContextPath: /
  type: simple
  rootPath: /api/*
  connector:
    type: http
    port: 8002

value: value

logging:
  level: INFO
  loggers:
    eu.atos: DEBUG
    org.glassfish: DEBUG
