server:
  applicationContextPath: /
  type: simple
  rootPath: /api/*
  connector:
    type: http
    port: 8080

value: value

logging:
  level: INFO
  loggers:
    eu.atos: DEBUG
    org.glassfish: DEBUG
